config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :teams
  resources :comments
  resources :custom_threads
  resources :admincontrols
  resources :projects do
    collection do
      get :dashboard
      post :upload
      delete :destroyattachment
    end
  end
  resources :students
  get 'login', to: 'sessions#new', as: 'login'
  get 'sessions/create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: 'signup'
  resources :users do
    collection do
      get :role
      get :delete
      get :admin
      get :profile
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'projects#dashboard'
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :project
    validates :title, presence:true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project_id, only: [:new, :show, :edit, :destroy]
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :checkAccess, only: [:new, :show, :edit, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    if params.has_key?(:id) && params[:id] != ""
      @tasks = Task.where(project_id: params[:id])
      @id = params[:id]
      @project = Project.where(id: params[:id])
    else
      redirect_back fallback_location: root_path
    end
    
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @id = params[:id]
    @user_id = session[:user_id]
  end

  # GET /tasks/1/edit
  def edit
    @pid = params[:project_id]
    @uid = session[:user_id]
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:project_id, :user_id, :title)
    end

    def set_project_id
      if action_name == 'edit'
        @projectId = params[:project_id]
      elsif action_name == 'new'
        @projectId = params[:id]
      elsif action_name == 'destroy'
        @projectId = params[:project_id]
      end
    end 

    def checkAccess
      @participants = Team.where(project_id: @projectId)
      @user = @participants.select { |i| i.user_id == session[:user_id] }       
      @access = Hash.new
      @access['show'] =  @user[0].read_access
      @access['new'] = @user[0].write_access
      @access['edit'] =  @user[0].update_access
      @access['delete'] =  @user[0].delete_access
      unless @access[action_name] == 1
        flash[:access_error] = "you dont have access to perform this action."
        redirect_back fallback_location: root_url
      end
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= form.label :project_id %>
    <%= form.hidden_field :project_id, value: project_id %>
  </div>

  <div class="field">
    <%#= form.label :user_id %>
    <%= form.hidden_field :user_id, value: user_id %>
  </div>

  <div class="field">
    <%#= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div id="page-wrapper">
<div class="container-fluid">
<div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">All Tasks</h4> </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><%= link_to 'Tasks', tasks_path(id: @pid) %></li> | 
                <li><a href="#" class="active">Edit task</a></li>
            </ol>
        </div>
        <!-- /.col-lg-12 -->
    </div>
<div class="row">
<div class="col-md-12 col-lg-12 col-sm-12">
    <div class="white-box">
        <h3 class="box-title">Edit Task for <%= @task.title %></h3>
        <div class="table-responsive">
        <p id="notice"><%= notice %></p>
        <%= render 'form', task: @task, project_id: @pid, user_id: @uid %>
        
        </div>
    </div>
</div>
</div>
</div>
<!-- /.container-fluid -->
<footer class="footer text-center"> 2020 &copy; Basecamp1 brought to you by outsoureceglobal.com </footer>
</div>

app/views/tasks/index.html.erb
<div id="page-wrapper">
<div class="container-fluid">
<div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">All Tasks</h4> </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="/projects/<%= @project[0].id %>"><%= @project[0].title %></a></li> | 
                <li><a href="#" class="active">New Project</a></li>
            </ol>
        </div>
        <!-- /.col-lg-12 -->
    </div>
<div class="row">
<div class="col-md-12 col-lg-12 col-sm-12">
    <div class="white-box">
        <h3 class="box-title">Tasks for <%= @project[0].title %></h3>
        <div class="table-responsive">
        <p id="notice"><%= notice %></p>
        <%= link_to 'New Task', new_task_path(id:@id), class: "btn btn-success btn-sm", style: "color:#fff" %>
        <div class = "table-reponsive">
        <% if flash[:access_error] %>
          <div class="alert alert-danger">
            <strong>Sorry!</strong> <%= flash[:access_error] %>
          </div>
        <% end %>
          <table class="table">
            <thead>
              <tr>
                <th>#</th>
                <th>Title</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% 
              count = 1
              @tasks.each do |task| %>
                <tr>
                  <td><%= count %></td>
                  <td><%= task.title %></td>
                  <td><%= link_to 'Show', task %></td>
                  <td><%= link_to 'Edit', edit_task_path(task, project_id: task.project_id) %></td>
                  <td><%= link_to 'Delete', task_path(task.id, project_id: task.project_id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% 
              count = count + 1
              end %>
            </tbody>
          </table>
        </div>
        </div>
    </div>
</div>
</div>
</div>
<!-- /.container-fluid -->
<footer class="footer text-center"> 2020 &copy; Basecamp1 brought to you by outsoureceglobal.com </footer>
</div>

app/views/tasks/new.html.erb
<div id="page-wrapper">
<div class="container-fluid">
<div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">New Tasks</h4> </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><%= link_to 'Tasks', tasks_path(id: @pid) %></li> | 
                <li><a href="#" class="active">New task</a></li>
            </ol>
        </div>
        <!-- /.col-lg-12 -->
    </div>
<div class="row">
<div class="col-md-12 col-lg-12 col-sm-12">
    <div class="white-box">
        <h3 class="box-title">New Task</h3>
        <div class="table-responsive">
        <p id="notice"><%= notice %></p>
        <%= render 'form', task: @task, project_id: @id, user_id: @user_id %>
        
        </div>
    </div>
</div>
</div>
</div>
<!-- /.container-fluid -->
<footer class="footer text-center"> 2020 &copy; Basecamp1 brought to you by outsoureceglobal.com </footer>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @task.project_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>