config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :teams
  resources :comments
  resources :custom_threads
  resources :admincontrols
  resources :projects do
    collection do
      get :dashboard
      post :upload
      delete :destroyattachment
    end
  end
  resources :students
  get 'login', to: 'sessions#new', as: 'login'
  get 'sessions/create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: 'signup'
  resources :users do
    collection do
      get :role
      get :delete
      get :admin
      get :profile
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'projects#dashboard'
end

app/models/admincontrol.rb
class Admincontrol < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :CustomThread, optional: true
    belongs_to :user
end

app/models/custom_thread.rb
class CustomThread < ApplicationRecord
    belongs_to :project
    has_many :comments, dependent: :destroy

    validates :title, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    has_many_attached :file
    has_many :CustomThreads, dependent: :destroy
    has_many :Teams, dependent: :destroy
    has_many :Tasks, dependent: :destroy

    validates :title, presence:true
    validates :description, presence:true
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :assignments  
    has_many :users, through: :assignments
    validates :name, presence: true, uniqueness: true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :project
    validates :title, presence:true
end

app/models/team.rb
class Team < ApplicationRecord
    #validates_uniqueness_of :user_id, scope: :project_id
    belongs_to :user
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
    
    EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i
    validates :username, presence:true, :uniqueness => true, :length => { :in => 3..20 }
    validates :password, presence:true, length: { minimum: 6 }, on: :create
    validates :email, presence:true, :uniqueness => true, :format => EMAIL_REGEX
    has_secure_password

    has_many :assignments  
    has_many :roles, through: :assignments
    has_many :project
    has_many :comment
    has_many :team

    def role?(role)  
        roles.any? { |r| r.name.underscore.to_sym == role }  
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project_id, only: [:new, :show, :edit, :destroy]
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :checkAccess, only: [:new, :show, :edit, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    if params.has_key?(:id) && params[:id] != ""
      @tasks = Task.where(project_id: params[:id])
      @id = params[:id]
      @project = Project.where(id: params[:id])
    else
      redirect_back fallback_location: root_path
    end
    
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @id = params[:id]
    @user_id = session[:user_id]
  end

  # GET /tasks/1/edit
  def edit
    @pid = params[:project_id]
    @uid = session[:user_id]
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:project_id, :user_id, :title)
    end

    def set_project_id
      if action_name == 'edit'
        @projectId = params[:project_id]
      elsif action_name == 'new'
        @projectId = params[:id]
      elsif action_name == 'destroy'
        @projectId = params[:project_id]
      end
    end 

    def checkAccess
      @participants = Team.where(project_id: @projectId)
      @user = @participants.select { |i| i.user_id == session[:user_id] }       
      @access = Hash.new
      @access['show'] =  @user[0].read_access
      @access['new'] = @user[0].write_access
      @access['edit'] =  @user[0].update_access
      @access['delete'] =  @user[0].delete_access
      unless @access[action_name] == 1
        flash[:access_error] = "you dont have access to perform this action."
        redirect_back fallback_location: root_url
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :is_admin, only: [:admin]
    def index
        @users = User.all
    end

    def new
    end

    def admin
        @users = User.all
        @projects = Project.all
    end

    def profile
        @user = User.find(session[:user_id])
    end

    
    def create
        @users = User.new(user_params)
        if @users.save
            session[:user_id] = @users.id
            redirect_to projects_path
        else
            redirect_to new_user_path
            flash[:errors] = @users.errors.full_messages
        end
    end

    # GET /projects/1/edit
    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        respond_to do |format|
            if @user.update(user_update_params)
              return redirect_to profile_users_path
              format.html { redirect_to @user, notice: 'Project was successfully updated.' }
              format.json { render :show, status: :ok, location: @user }
            else
              format.html { render :edit }
              format.json { render json: @user.errors, status: :unprocessable_entity }
            end
          end
    end

    def show
        @user = User.find(params[:id])
    end

    def delete
        @user = User.find(params[:id])
        if @user.destroy
            redirect_to users_path
        end
    end

    def role
        @user = User.find(params[:id])
        if @user.admin_access > 0
            @user.update_column(:admin_access, 0);
            @user.save
            redirect_to admin_users_path
        elsif
            @user.update_column(:admin_access, 1);
            @user.save
            redirect_to admin_users_path
        end
    end

    private
        def user_params
            params.require(:user).permit(:username, :password, :email)
        end
    private
        def user_update_params
            params.require(:user).permit(:username, :email)
        end
        def is_admin
            user = User.find(session[:user_id])
            unless user.admin_access == 1
              redirect_back fallback_location: root_path
            end
        end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/controlpanel_helper.rb
module ControlpanelHelper
end

app/helpers/controls_helper.rb
module ControlsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
    <div class="field">
      <label for="username">Username</label>
      <%= form.text_field :username, class: "form-control", id: "username" %>
    </div>
  
    <div class="field">
      <label for="password">Password</label>
      <%= form.text_field :password, class: "form-control", id: "password" %>
    </div>

    <div class="field">
      <label for="email">Email</label>
      <%= form.text_field :email, class: "form-control", id: "email" %>
    </div>
  
  
    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/users/admin.html.erb
<div id="page-wrapper">
<div class="container-fluid">
<div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">ADMIN CONTROL PANEL</h4> </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="#" class="active">Control Panel</a></li>
            </ol>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <div class="row">
        <div class="col-lg-4 col-sm-6 col-xs-12">
            <div class="white-box analytics-info">
                <h3 class="box-title">Total Users</h3>
                <ul class="list-inline two-part">
                    <li>
                        <div id="sparklinedash"></div>
                    </li>
                    <li class="text-right"><i class="ti-arrow-up text-success"></i> <span class="counter text-success"><%= @users.size%></span></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 col-xs-12">
            <div class="white-box analytics-info">
                <h3 class="box-title">Total Projects Created</h3>
                <ul class="list-inline two-part">
                    <li>
                        <div id="sparklinedash2"></div>
                    </li>
                    <li class="text-right"><i class="ti-arrow-up text-purple"></i> <span class="counter text-purple"><%= @projects.size%></span></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 col-xs-12">
            <div class="white-box analytics-info">
                <h3 class="box-title">Unique Visitor</h3>
                <ul class="list-inline two-part">
                    <li>
                        <div id="sparklinedash3"></div>
                    </li>
                    <li class="text-right"><i class="ti-arrow-up text-info"></i> <span class="counter text-info">911</span></li>
                </ul>
            </div>
        </div>
    </div>
<div class="row">
<div class="col-md-12 col-lg-12 col-sm-12">
    <div class="white-box">
        <h3 class="box-title">WELCOME ADMIN</h3>
        <div class="table-responsive">
            <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>USERNAME</th>
                    <th>EMAIL</th>
                    <th>ROLES</th>
                    <th>ACTION</th>
                </tr>
            </thead>
            <tbody>
                <% 
                count = 1
                @users.each do |user|
                if user.admin_access == 1
                    texts = "Admin"
                    clas = "danger"
                else
                    texts = "User"
                    clas = "success"
                end
                %>
                <tr>
                    <td><%= count %></td>
                    <td class="txt-oflo"><%= user.username %></td>
                    <td><%= user.email %></td>
                    <td class="txt-oflo"><button class="btn btn-<%= clas %> btn-sm"><%= texts %></button></td>
                    <td><span class="text-success">
                    <% user.admin_access == 0 ? text = "Make Admin" : text = "Remove Admin Access" %>
                    <%= link_to 'Edit', edit_user_path(user) %> | <%= link_to text, role_users_path(:id => user.id) %>
                    </span></td>
                </tr>
                <%
                count = count + 1
                end %>
                
            </tbody>
            </table>
        </div>
    </div>
</div>
</div>
<div class="row">
<div class="col-md-12 col-lg-12 col-sm-12">
    <div class="white-box">
        <% if flash[:error] %>
        <div class="alert alert-danger alert-dismissible fade show"><%= flash[:error] %>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
        <% end %>
        <% if flash[:access_error] %>
        <div class="alert alert-danger alert-dismissible fade show"><%= flash[:access_error] %>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
        <% end %>
        <h3 class="box-title">All PROJECTS</h3>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>TITLE</th>
                        <th>DESCRIPTION</th>
                        <th>AUTHOR</th>
                        <th>DATE CREATED</th>
                        <th>ACTION</th>
                    </tr>
                </thead>
                <tbody>
                    <% 
                    count = 1
                    @projects.each do |p|
                    %>
                    <tr>
                        <td><%= count %></td>
                        <td class="txt-oflo"><%= p.title.titleize %></td>
                        <td><%= p.description.slice(0,1).capitalize + p.description.slice(1..-1) %></td>
                        <td class="txt-oflo"><%= p.user.username %></td>
                        <td class="txt-oflo"><i><%= p.created_at.strftime(" %B %d, %Y") %></i></td>
                        <td><span class="text-success">
                        <%= link_to 'Show', project_path(p) %> | <%= link_to 'Edit', edit_project_path(p) %> | <%= link_to 'Delete', p, method: :delete, data: { confirm: 'Are you sure?' } %> 
                        
                        </span></td>
                    </tr>
                    <%
                    count = count + 1
                    end %>
                    
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
</div>
</div>





app/views/users/edit.html.erb
<div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">Profile page</h4>
                    </div>
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        
                        <ol class="breadcrumb">
                            <li><a href="<%= admin_users_path()%>">Control Panel</a></li> | 
                            <li class="active">Edit User Profile</li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->
                <!-- .row -->
                <div class="row">
                    <div class="col-md-12 col-xs-12">
                        <div class="white-box">
                        <p id="notice"><%= notice %></p>
                        <%= render 'form', user: @user %>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
            <footer class="footer text-center"> 2017 &copy; Ample Admin brought to you by wrappixel.com </footer>
        </div>

app/views/users/index.html.erb
<div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">Profile page</h4>
                    </div>
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        
                        <ol class="breadcrumb">
                            <li><a href="<%= projects_path()%>">Dashboard</a></li> | 
                            <li class="active">Profile Page</li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->
                <!-- .row -->
                <div class="row">
                    <div class="col-md-4 col-xs-12">
                        <div class="white-box">
                            <div class="user-bg"> <img width="100%" alt="user" src="../plugins/images/large/img1.jpg">
                                <div class="overlay-box">
                                    <div class="user-content">
                                        <a href="javascript:void(0)"><img src="../plugins/images/users/genu.jpg"
                                                class="thumb-lg img-circle" alt="img"></a>
                                        <h4 class="text-white"><%= User.find(session[:user_id]).username %></h4>
                                        <h5 class="text-white"><%= User.find(session[:user_id]).email %></h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8 col-xs-12">
                        <div class="white-box">
                        <%= render 'form', user: @user %>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
            <footer class="footer text-center"> 2017 &copy; Ample Admin brought to you by wrappixel.com </footer>
        </div>

app/views/users/new.html.erb
<div class="form-wrapper">
<h1>Register New User</h1>

<% if flash[:errors]%>
    <% flash[:errors].each do |error|%>
        <p style="color:red"><%= error%></p>
    <%end%>
<%end%>
<%= form_with scope: :user, url: users_path, local: true do |form| %>
    <div class="input-wrapper">
      <%= form.label :username %>
      <%= form.text_field :username %>
    </div>
   
    <div class="input-wrapper">
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>

    <div class="input-wrapper">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>

    <div class="input-wrapper">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>

    <div class="check">
      <input type="checkbox" id="checkbox">
      <label for="checkbox">I agree terms & conditions</label>
    </div>
      <%= form.submit({:class => 'btn btn-sm btn-primary'}) %>
      <%= link_to 'Go to login', login_path %>
<% end %>

<%= javascript_pack_tag 'user' %>
</div>

app/views/users/profile.html.erb
<div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">Profile page</h4>
                    </div>
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        
                        <ol class="breadcrumb">
                            <li><a href="<%= projects_path()%>">Dashboard</a></li> | 
                            <li class="active">Profile Page</li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->
                <!-- .row -->
                <div class="row">
                    <div class="col-md-4 col-xs-12">
                        <div class="white-box">
                            <div class="user-bg"> <img width="100%" alt="user" src="../plugins/images/large/img1.jpg">
                                <div class="overlay-box">
                                    <div class="user-content">
                                        <a href="javascript:void(0)"><img src="../plugins/images/users/genu.jpg"
                                                class="thumb-lg img-circle" alt="img"></a>
                                        <h4 class="text-white"><%= User.find(session[:user_id]).username %></h4>
                                        <h5 class="text-white"><%= User.find(session[:user_id]).email %></h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8 col-xs-12">
                        <div class="white-box">
                        <%= render 'form', user: @user %>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
            <footer class="footer text-center"> 2017 &copy; Ample Admin brought to you by wrappixel.com </footer>
        </div>

app/views/users/role.html.erb
<%= @user.admin_access %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-3">
    <div style="width:100%; background:#fff; height:200px"></div>
  </div>
  <div class="col-sm-6">
  <div style="width:100%; background:#fff; height:200px; padding:10px 10px">
    <p>
    <strong>Username:</strong>
    <%= @user.username %>
    </p>

    <p>
    <strong>Password:</strong>
    <%= @user.password %>
    </p>

    <p>
    <strong>Email:</strong>
    <%= @user.email %>
    </p>
    <%= link_to 'Delete', delete_users_path(:id => @user.id), :class=>"btn btn-danger" %>
    <% @user.admin_access == 0 ? text = "Make admin" : text = "Remove admin access" %>
  <a class = "btn btn-primary" style="color:#fff" href="<%= role_users_path(:id => @user.id) %>"><%= text %></a>
  </div>
    
  </div>
  <div class="col-sm-3">
  <%= link_to 'Edit', edit_user_path(@user) %>
  
  </div>
</div>