config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :teams
  resources :comments
  resources :custom_threads
  resources :admincontrols
  resources :projects do
    collection do
      get :dashboard
      post :upload
      delete :destroyattachment
    end
  end
  resources :students
  get 'login', to: 'sessions#new', as: 'login'
  get 'sessions/create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: 'signup'
  resources :users do
    collection do
      get :role
      get :delete
      get :admin
      get :profile
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'projects#dashboard'
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    has_many_attached :file
    has_many :CustomThreads, dependent: :destroy
    has_many :Teams, dependent: :destroy
    has_many :Tasks, dependent: :destroy

    validates :title, presence:true
    validates :description, presence:true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :destroy]
  before_action :authorized, only: [:index, :show, :edit, :update, :destroy]
  #before_action :current_user_required, only: [ :edit, :update, :destroy ]
  before_action :checkAccess, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index()
    @projects = Project.where(:id => Team.select(:project_id).where(user_id: session[:user_id] ).map(&:project_id))
    
    @users = User.all
  end

  def dashboard()
    @projects = Project.where(:id => Team.select(:project_id).where(user_id: session[:user_id] ).map(&:project_id)).order(created_at: :desc).limit(5)
    @users = User.where(id: session[:user_id])
    @shared = Team.where(user_id: session[:user_id])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    #@attachment = Project.find(15)
    #@attachment.file.attach(params[:files])
    @comment = Comment.new
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = session[:user_id]

    respond_to do |format|
      if @project.save
        @team = Team.new
        @team.project_id = @project.id
        @team.user_id = session[:user_id]
        @team.read_access = 1
        @team.write_access = 1
        @team.update_access = 1
        @team.delete_access = 1
        @team.save
        return redirect_to projects_path
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroyattachment
    redirect_to project_path
  end

  def upload
      @project = Project.find(params[:projectId])
      @project.file.attach(params[:files])
      if @project.save
        redirect_back fallback_location: root_path
      end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        return redirect_to projects_path
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, file: [])
    end

    def team_params
      params.require(:team).permit(:project_id, :user_id, :read_access, :write_access, :update_access, :delete_access)
    end

  private 
    def current_user_required
      unless current_user == @project.user
        flash[:error] = 'Sorry you are not permitted to perform such action! '
        redirect_back fallback_location: root_path
      end
    end

    def checkAccess
      @participants = Team.where(project_id: @project)
      @user = @participants.select { |i| i.user_id == session[:user_id] }       
      @access = Hash.new
      @access['show'] =  @user[0].read_access
      @access['new'] = @user[0].write_access
      @access['edit'] =  @user[0].update_access
      @access['delete'] =  @user[0].delete_access
      unless @access[action_name] == 1 || current_user == @project.user
        flash[:access_error] = "you dont have access to perform this action."
        redirect_back fallback_location: root_url
      end
    end

    
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="title">Project Title</label>
    <%= form.text_field :title, placeholder: "Add project title", class: "form-control", id: "title" %>
  </div>

  <div class="field">
    <label for="description">Project Description</label>
    <%= form.text_field :description, placeholder: "Add project description", class: "form-control", id: "description" %>
  </div>

  <%= form.file_field :file, class: "file", id:"file-demo", lang:"es", multiple: true %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_form_comment.html.erb
<%= form_with(model: comment, local: true) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
  
        <ul>
          <% comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%#= form.label :custom_thread_id %>
      <%= form.hidden_field :custom_thread_id, value: thread_id %>
    </div>
  
    <div class="field">
      <%#= form.label :user_id %>
      <%= form.hidden_field :user_id, value: user_id %>
    </div>
  
    <div class="field">
      <label for="comment">Comment:</label>
      <%= form.text_area :comment, class:"form-control", rows:"5" %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/projects/dashboard.html.erb
<div id="page-wrapper">
<div class="container-fluid">
    <div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">Dashboard</h4> </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="#">Dashboard</a></li>
            </ol>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <!-- ============================================================== -->
    <!-- Different data widgets -->
    <!-- ============================================================== -->
    <!-- .row -->
    <div class="row">
        <div class="col-lg-4 col-sm-6 col-xs-12">
            <div class="white-box analytics-info">
                <h3 class="box-title">Total Users</h3>
                <ul class="list-inline two-part">
                    <li>
                        <div id="sparklinedash"></div>
                    </li>
                    <li class="text-right"><i class="ti-arrow-up text-success"></i> <span class="counter text-success"><%= @users.size%></span></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 col-xs-12">
            <div class="white-box analytics-info">
                <h3 class="box-title">Total Projects Created</h3>
                <ul class="list-inline two-part">
                    <li>
                        <div id="sparklinedash2"></div>
                    </li>
                    <li class="text-right"><i class="ti-arrow-up text-purple"></i> <span class="counter text-purple"><%= @projects.size%></span></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 col-xs-12">
            <div class="white-box analytics-info">
                <h3 class="box-title">Total Project Shared</h3>
                <ul class="list-inline two-part">
                    <li>
                        <div id="sparklinedash3"></div>
                    </li>
                    <li class="text-right"><i class="ti-arrow-up text-info"></i> <span class="counter text-info"><%= @shared.size%></span></li>
                </ul>
            </div>
        </div>
    </div>
    <!--/.row -->
    <!--row -->
    <!-- /.row -->
    <!-- ============================================================== -->
    <!-- table -->
    <!-- ============================================================== -->
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12">
            <div class="white-box">
                <h3 class="box-title">All users</h3>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>USERNAME</th>
                                <th>EMAIL</th>
                                <th>ROLES</th>
                                <th>ACTION</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% 
                            count = 1
                            @users.each do |user|
                            if user.admin_access == @admin
                                text = "Admin"
                                clas = "danger"
                            else
                                text = "User"
                                clas = "success"
                            end
                            %>
                            <tr>
                                <td><%= count %></td>
                                <td class="txt-oflo"><%= user.username %></td>
                                <td><%= user.email %></td>
                                <td class="txt-oflo"><button class="btn btn-<%= clas %> btn-sm"><%= text %></button></td>
                                <td><span class="text-success">
                                <%= link_to 'Show', user_path(user) %> | <%= link_to 'Projects', projects_path(user.id) %> | 
                                <%= link_to 'Edit', edit_user_path(user) %>
                                </span></td>
                            </tr>
                            <%
                            count = count + 1
                            end %>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- chat-listing & recent comments -->
    <!-- ============================================================== -->
    <div class="row">
        <!-- .col -->
        <div class="col-md-12 col-lg-12 col-sm-12">
            <div class="white-box">
            <h3 class="box-title">Latest PROJECTS</h3>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>TITLE</th>
                            <th>DESCRIPTION</th>
                            <th>AUTHOR</th>
                            <th>DATE CREATED</th>
                            <th>ACTION</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% 
                        count = 1
                        @projects.each do |p|
                        %>
                        <tr>
                            <td><%= count %></td>
                            <td class="txt-oflo"><%= p.title.titleize %></td>
                            <td><%= p.description.slice(0,1).capitalize + p.description.slice(1..-1) %></td>
                            <td class="txt-oflo"><%= p.user.username %></td>
                            <td class="txt-oflo"><i><%= p.created_at.strftime(" %B %d, %Y") %></i></td>
                            <td><span class="text-success">
                            <%= link_to 'Show', project_path(p) %> | <%= link_to 'Edit', edit_project_path(p) %> | <%= link_to 'Delete', p, method: :delete, data: { confirm: 'Are you sure?' } %> 
                            
                            </span></td>
                        </tr>
                        <%
                        count = count + 1
                        end %>
                        
                    </tbody>
                </table>
            </div>
            </div>
        </div>
        <!-- /.col -->
    </div>
</div>
<!-- /.container-fluid -->
<footer class="footer text-center"> 2020 &copy; Basecamp1 brought to you by outsoureceglobal.com </footer>
</div>

app/views/projects/edit.html.erb
<div id="page-wrapper">
<div class="container-fluid">
<div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">Edit Project</h4> </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="<%= projects_path()%>">Projects</a></li> | 
                <li><a href="#" class="active">Edit Project</a></li>
            </ol>
        </div>
        <!-- /.col-lg-12 -->
    </div>
<div class="row">
<div class="col-md-12 col-lg-12 col-sm-12">
    <div class="white-box">
        <h3 class="box-title">Edit Project</h3>
        <div class="table-responsive">
        <%= render 'form', project: @project %>
        </div>
    </div>
</div>
</div>
</div>
<!-- /.container-fluid -->
<footer class="footer text-center"> 2020 &copy; Basecamp1 brought to you by outsoureceglobal.com </footer>
</div>

app/views/projects/index.html.erb
<div id="page-wrapper">
<div class="container-fluid">
<div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">Projects</h4> </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="<%= dashboard_projects_path()%>">Dashboard</a></li> | 
                <li><a href="#" class="active">Projects</a></li>
            </ol>
        </div>
        <!-- /.col-lg-12 -->
    </div>
<div class="row">
<div class="col-md-12 col-lg-12 col-sm-12">
    <div class="white-box">
        <% if flash[:error] %>
        <div class="alert alert-danger alert-dismissible fade show"><%= flash[:error] %>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
        <% end %>
        <% if flash[:access_error] %>
          <div class="alert alert-danger">
            <strong>Sorry!</strong> <%= flash[:access_error] %>
          </div>
        <% end %>
        <div class="col-md-3 col-sm-4 col-xs-6 pull-right">
        <a href="<%= new_project_path %>" class="btn btn-danger add pull-right btn-sm" role="button" style="color:#fff"><i class="fa fa-plus"></i> Add New</a>
        </div>
        <h3 class="box-title">All PROJECTS</h3>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>TITLE</th>
                        <th>DESCRIPTION</th>
                        <th>AUTHOR</th>
                        <th>DATE CREATED</th>
                        <th>ACTION</th>
                    </tr>
                </thead>
                <tbody>
                    <% 
                    count = 1
                    @projects.each do |p|
                    %>
                    <tr>
                        <td><%= count %></td>
                        <td class="txt-oflo"><%= p.title.titleize %></td>
                        <td><%= p.description.slice(0,1).capitalize + p.description.slice(1..-1) %></td>
                        <td class="txt-oflo"><%= p.user.username %></td>
                        <td class="txt-oflo"><i><%= p.created_at.strftime(" %B %d, %Y") %></i></td>
                        <td><span class="text-success">
                        <%= link_to 'Show', project_path(p) %> | <%= link_to 'Edit', edit_project_path(p) %> | <%= link_to 'Delete', p, method: :delete, data: { confirm: 'Are you sure?' } %> 
                        
                        </span></td>
                    </tr>
                    <%
                    count = count + 1
                    end %>
                    
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
</div>
<!-- /.container-fluid -->
<footer class="footer text-center"> 2020 &copy; Basecamp1 brought to you by outsoureceglobal.com </footer>
</div>

app/views/projects/new.html.erb
<div id="page-wrapper">
<div class="container-fluid">
<div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">New Project</h4> </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="<%= projects_path()%>">Projects</a></li> | 
                <li><a href="#" class="active">New Project</a></li>
            </ol>
        </div>
        <!-- /.col-lg-12 -->
    </div>
<div class="row">
<div class="col-md-12 col-lg-12 col-sm-12">
    <div class="white-box">
        <h3 class="box-title">Add Project</h3>
        <div class="table-responsive">
        <%= render 'form', project: @project %>
        </div>
    </div>
</div>
</div>
</div>
<!-- /.container-fluid -->
<footer class="footer text-center"> 2020 &copy; Basecamp1 brought to you by outsoureceglobal.com </footer>
</div>